### ISSUE TITLE
ActiveRecord::RecordNotFound at /users/[object%20Object] Couldn't find User with 'id'=[object Object] after onetouch authentication

### ISSUE THREAD

**Issue by wxxiao33** [twilio/authy-devise#135]
When login, after one touch authentication, my app will redirect to http://localhost:3000/users/[object%20Object] and get an error, but if I authenticated by entering the token (authy or SMS), it will redirect to the right path: http://localhost:3000/users/3
I followed the basic setup steps, could you please help me figure it out?

my routes.rb looks like this:
```
  devise_for :users, controllers: { 
        omniauth_callbacks: 'users/omniauth',
        verify_authy: "/verify-token",
        enable_authy: "/enable-two-factor",
        verify_authy_installation: "/verify-installation",
        authy_onetouch_status: "/onetouch-status"
                                  }

  resources :users
```

**Comment by philnash** [comment]
That redirect is controlled by this code: https://github.com/twilio/authy-devise/blob/master/app/views/devise/verify_authy.html.erb#L31

Have you changed anything in that JS on your app? Or what is returned from [the controller action](https://github.com/twilio/authy-devise/blob/master/app/controllers/devise/devise_authy_controller.rb#L124)?

**Comment by wxxiao33** [comment]
Thank you for replying. I am pretty new to ruby on rails. I don't think I changed my JS but I'm not completely sure.

I also tried to custom redirect paths, I created ./app/controllers/users/devise_authy_controller.rb 
```
class User::DeviseAuthyController < Devise::DeviseAuthyController

  protected
    def after_authy_enabled_path_for(resource)
      root_path
    end

    def after_authy_verified_path_for(resource)
      root_path
    end

    def after_authy_disabled_path_for(resource)
      root_path
    end

    def invalid_resource_path
      new_user_session_path
    end
end
```

and change my routes.rb like this
```
  devise_for :users, controllers: { 
        omniauth_callbacks: 'users/omniauth',
        devise_authy: 'users/devise_authy',
        verify_authy: "/verify-token",
        enable_authy: "/enable-two-factor",
        verify_authy_installation: "/verify-installation",
        authy_onetouch_status: "/onetouch-status"
                                  }

  resources :users
```
NameError at /users/verify_authy
uninitialized constant Users::DeviseAuthyController

**Comment by philnash** [comment]
Hmm, your `NameError` at the bottom of your comment looks like it's because you have defined a `User::DeviseAuthyController` but if your Devise is set up to route to `devise_for :users` then you should probably use a plural "users" too. 

So, make sure your new controller is actually a `Users::DeviseAuthyController` (note the "s" in "Users").

Have you modified `after_sign_in_path_for` anywhere in your Devise setup?

**Comment by wxxiao33** [comment]
Yes, you are right, I should use `Users`. But after change it to `Users`, it still have `Couldn't find User with 'id'=[object Object]` error.

I haven't modified `after_sign_in_path_for` anywhere. It is really confusing because token authentication works just fine.

Maybe it is a dump question, but how can I check what is returned from the controller action? Here is the log from my console:
```
Started POST "/users/sign_in" for ::1 at 2020-04-24 02:07:16 -0400
Processing by Devise::SessionsController#create as HTML
  Parameters: {"authenticity_token"=>"esBBqnzyazLAoVxRnx/B4rEAGO/wsa5ymYThw1aEEatSyCBxYMI0Dpx4IcDRg1DkGOv10L0xzZGCSZ4DVCDbuQ==", "user"=>{"email"=>"infinityxwx123@gmail.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Log in"}
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "infinityxwx123@gmail.com"], ["LIMIT", 1]]
Redirected to http://localhost:3000/users/verify_authy
Filter chain halted as :check_request_and_redirect_to_verify_token rendered or redirected
Completed 302 Found in 126ms (ActiveRecord: 9.3ms | Allocations: 3800)


   (0.2ms)  BEGIN
  ActiveRecord::SessionStore::Session Update (0.6ms)  UPDATE "sessions" SET "data" = $1, "updated_at" = $2 WHERE "sessions"."id" = $3  [["data", "BAh7CEkiDHVzZXJfaWQGOgZFVGkISSIadXNlcl9wYXNzd29yZF9jaGVja2Vk\nBjsAVFRJIhV1c2VyX3JlbWVtYmVyX21lBjsAVEY=\n"], ["updated_at", "2020-04-24 06:07:16.718430"], ["id", 71]]
   (1.5ms)  COMMIT
Started GET "/users/verify_authy" for ::1 at 2020-04-24 02:07:16 -0400
Processing by Users::DeviseAuthyController#GET_verify_authy as HTML
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
  Rendering devise/devise_authy/verify_authy.html.erb within layouts/application
  Rendered devise/devise_authy/verify_authy.html.erb within layouts/application (Duration: 2.4ms | Allocations: 984)
  Rendered layouts/_rails_default.html.erb (Duration: 4.2ms | Allocations: 1951)
  Rendered layouts/_shim.html.erb (Duration: 0.0ms | Allocations: 5)
  Rendered layouts/_header.html.erb (Duration: 0.7ms | Allocations: 168)
  Rendered layouts/_footer.html.erb (Duration: 0.1ms | Allocations: 5)
Completed 200 OK in 177ms (Views: 23.5ms | ActiveRecord: 0.5ms | Allocations: 14524)


   (0.4ms)  BEGIN
  ActiveRecord::SessionStore::Session Update (0.7ms)  UPDATE "sessions" SET "data" = $1, "updated_at" = $2 WHERE "sessions"."id" = $3  [["data", "BAh7CUkiDHVzZXJfaWQGOgZFVGkISSIadXNlcl9wYXNzd29yZF9jaGVja2Vk\nBjsAVFRJIhV1c2VyX3JlbWVtYmVyX21lBjsAVEZJIhBfY3NyZl90b2tlbgY7\nAEZJIjFyVHM0VnJ2WkNCZlV4RnpzRTk3Y1FIVkpmcGFsanQ5YkxabVlVbXBP\nRlRvPQY7AEY=\n"], ["updated_at", "2020-04-24 06:07:16.927417"], ["id", 71]]
   (1.6ms)  COMMIT
Started GET "/users/authy_onetouch_status?onetouch_uuid=c68ce9e0-681f-0138-30f2-0a259c954b0d" for ::1 at 2020-04-24 02:07:20 -0400
Processing by Users::DeviseAuthyController#GET_authy_onetouch_status as */*
  Parameters: {"onetouch_uuid"=>"c68ce9e0-681f-0138-30f2-0a259c954b0d"}
  User Load (1.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
Completed 202 Accepted in 44ms (ActiveRecord: 1.4ms | Allocations: 2034)


Started GET "/users/authy_onetouch_status?onetouch_uuid=c68ce9e0-681f-0138-30f2-0a259c954b0d" for ::1 at 2020-04-24 02:07:23 -0400
Processing by Users::DeviseAuthyController#GET_authy_onetouch_status as */*
  Parameters: {"onetouch_uuid"=>"c68ce9e0-681f-0138-30f2-0a259c954b0d"}
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
Completed 202 Accepted in 34ms (ActiveRecord: 0.4ms | Allocations: 2023)


Started GET "/users/authy_onetouch_status?onetouch_uuid=c68ce9e0-681f-0138-30f2-0a259c954b0d" for ::1 at 2020-04-24 02:07:26 -0400
Processing by Users::DeviseAuthyController#GET_authy_onetouch_status as */*
  Parameters: {"onetouch_uuid"=>"c68ce9e0-681f-0138-30f2-0a259c954b0d"}
  User Load (1.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
   (0.3ms)  BEGIN
  User Update (0.5ms)  UPDATE "users" SET "last_sign_in_with_authy" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["last_sign_in_with_authy", "2020-04-24 06:07:26.167859"], ["updated_at", "2020-04-24 06:07:26.168325"], ["id", 3]]
   (1.5ms)  COMMIT
Completed 200 OK in 51ms (Views: 0.6ms | ActiveRecord: 3.5ms | Allocations: 6668)


   (0.2ms)  BEGIN
  ActiveRecord::SessionStore::Session Update (0.4ms)  UPDATE "sessions" SET "data" = $1, "updated_at" = $2 WHERE "sessions"."id" = $3  [["data", "BAh7DEkiDHVzZXJfaWQGOgZFVGkISSIadXNlcl9wYXNzd29yZF9jaGVja2Vk\nBjsAVFRJIhV1c2VyX3JlbWVtYmVyX21lBjsAVEZJIhBfY3NyZl90b2tlbgY7\nAEZJIjFyVHM0VnJ2WkNCZlV4RnpzRTk3Y1FIVkpmcGFsanQ5YkxabVlVbXBP\nRlRvPQY7AEZJIh11c2VyX2F1dGh5X3Rva2VuX2NoZWNrZWQGOwBUVEkiGXdh\ncmRlbi51c2VyLnVzZXIua2V5BjsAVFsHWwZpCEkiIiQyYSQxMSR1c3loUG55\nQnNMeWlUQXBZV2xOcWV1BjsAVEkiCmZsYXNoBjsAVHsHSSIMZGlzY2FyZAY7\nAFRbAEkiDGZsYXNoZXMGOwBUewZJIgtub3RpY2UGOwBGSSInU2lnbmVkIGlu\nIHdpdGggQXV0aHkgc3VjY2Vzc2Z1bGx5LgY7AFQ=\n"], ["updated_at", "2020-04-24 06:07:26.184512"], ["id", 72]]
   (1.3ms)  COMMIT
Started GET "/users/[object%20Object]" for ::1 at 2020-04-24 02:07:26 -0400
Processing by UsersController#show as HTML
  Parameters: {"id"=>"[object Object]"}
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", nil], ["LIMIT", 1]]
  ↳ app/controllers/users_controller.rb:89:in `set_user'
Completed 404 Not Found in 3ms (ActiveRecord: 0.4ms | Allocations: 1067)



ActiveRecord::RecordNotFound - Couldn't find User with 'id'=[object Object]:
  app/controllers/users_controller.rb:89:in `set_user'

Started POST "/__better_errors/60055648678a9349/variables" for ::1 at 2020-04-24 02:07:26 -0400
```

**Comment by philnash** [comment]
So yeah, the `after_sign_in_path_for` and `after_sign_up_path_for` methods need to return a path, not just any object. In this case, you changed it from returning a path to the current user object. 

When you sign in with One Touch the JS keeps checking the back-end to see if the sign in is complete. When it is complete, it sends a response with the result of `after_sign_in_path_for` in it. The JS tries to redirect to that path, but because you changed it to return `current_user` the JS serialized it into a string `[object Object]` which is where you see the error.

I think the reason it was working for the other methods was that [the controller actions were redirecting with something like](https://github.com/twilio/authy-devise/blob/master/app/controllers/devise/devise_authy_controller.rb#L36):

```ruby
respond_with resource, :location => after_sign_in_path_for(@resource)
```

You returned `current_user` for that and I think that some Rails magic means that `:location => user` would turn into `users_path(user)`.

It is safest to return a path from those `after_sign_in/up_path_for` methods and I'm glad you have done now. I'll close this issue, as it's not a problem with `devise-authy`, but feel free to keep asking questions.

**Comment by wxxiao33** [comment]
I guess I am still learning the magic of rails. Thank you for your help.

**Comment by philnash** [comment]
Yeah, this is one of those points where "Rails magic" doesn't help! Sorry you got caught up with this. Hopefully you're all sorted with it now.

**Comment by wxxiao33** [comment]
I am not sure if I need to open an new issue but I get
`ArgumentError at /users/verify-token
First argument in form cannot contain nil or be empty`
when I trying to use modals popup for log in and sign up. 

This error occurs when I tried to log in, after enter email and password in the log in modal, the verify-token page will give this error. I can still get onetouch push in my authy app and log in.


I create partial 'app/views/devise/sessions/_new.html.erb' with only the log in form:
```
<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: "card-body" }) do |f| %>

  <div class="form-group">
    <%= f.input :email,
                required: false,
                autofocus: true,
                class: "form-label",
                input_html: { autocomplete: "email" } %>
  </div>
  <div class="form-group">
    <%= f.input :password,
                required: false,
                class: "form-label",
                input_html: { autocomplete: "current-password" } %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="form-group">
      <%= f.label :remember_me, class: "form-checkbox" do %>
        <%= f.check_box :remember_me %>
        <i class="form-icon"></i> Remember me
      <% end %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.button :submit, "Log in", class: "btn btn-primary" %>
  </div>

  <a href="#SignUpModal" data-toggle="modal" data-dismiss="modal">Sign Up</a>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  
<% end %>
```
and similarity 'app/views/devise/registrations/_new.html.erb' for sign up:
```
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: "card-body" }) do |f| %>
        <%= f.error_notification %>

        <div class="form-group">
            <%= f.input :name,
                        class: "form-label"%>
        </div>

        <div class="form-group">
            <%= f.input :email,
                        autofocus: true,
                        class: "form-label",
                        input_html: { autocomplete: "email" }%>
        </div>

        <div class="form-group">
            <%= f.input :password,
                        class: "form-label",
                        hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                        input_html: { autocomplete: "new-password" } %>
        </div>

        <div class="form-group">
            <%= f.input :password_confirmation,
                        class: "form-label",
                        input_html: { autocomplete: "new-password" } %>
        </div>

        <div class="actions">
            <%= f.button :submit, "Sign up", class: "btn btn-primary" %>
        </div>
        
<% end %>
```
Then render them in the modals in my header partial 'app/views/layouts/_header.html_erb'.

I did some digging and I guess the reason is that `resource` helper is not available for the modals. So I add some helper function in my `app/helpers/application_helper.erb`
```
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class 
      User 
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
```
but I still get the same error. How could I get it to work with modal popups?

**Comment by philnash** [comment]
In the case of devise and this plugin, the `resource` is the `user` and never the `session` since you are logging a user into a session.

Try matching your sessions_helper to your registrations_helper and see if that helps.

**Comment by wxxiao33** [comment]
Sorry for the delayed reply, I think I break something when troubleshooting earlier because I tried to put these helper functions in `application_helper.rb`, but I still get the same error.
I actually change 'resource` to `:user` in these forms. Probably not the best way, but it works for now.

**Comment by philnash** [comment]
I think that’s what I meant to say. It shouldn’t ever be `session`. If this is for a user model, then `user` works. `resource` is the generic version for if you didn’t call your user model “user”.
