### ISSUE TITLE
NoMethodError (undefined method `qr_code' for #<Authy::Response:0x000055948144a7d0>):

### ISSUE THREAD

**Issue by diegopolido** [twilio/authy-devise#153]
### WHY

Endpoint: `/users/verify_authy_installation`

```
F, [2020-12-12T03:16:01.058885 #1244] FATAL -- : [c4d27567-8181-4f5a-9b1b-bc7acf7dd871]   
F, [2020-12-12T03:16:01.059118 #1244] FATAL -- : [c4d27567-8181-4f5a-9b1b-bc7acf7dd871] NoMethodError (undefined method `qr_code' for #<Authy::Response:0x000055948144a7d0>):
F, [2020-12-12T03:16:01.059182 #1244] FATAL -- : [c4d27567-8181-4f5a-9b1b-bc7acf7dd871]   
F, [2020-12-12T03:16:01.059274 #1244] FATAL -- : [c4d27567-8181-4f5a-9b1b-bc7acf7dd871] authy (2.7.5) lib/authy/response.rb:47:in `method_missing'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] devise-authy (2.2.0) app/controllers/devise/devise_authy_controller.rb:114:in `GET_verify_authy_installation'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/abstract_controller/base.rb:194:in `process_action'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] activesupport (5.2.4.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `block in instrument'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] activesupport (5.2.4.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `instrument'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] activerecord (5.2.4.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/abstract_controller/base.rb:134:in `process'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionview (5.2.4.1) lib/action_view/rendering.rb:32:in `process'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_controller/metal.rb:191:in `dispatch'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_controller/metal.rb:252:in `dispatch'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `each'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `serve'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] serviceworker-rails (0.6.0) lib/serviceworker/middleware.rb:35:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] exception_notification (4.4.0) lib/exception_notification/rack.rb:36:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] warden (1.2.8) lib/warden/manager.rb:34:in `catch'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] warden (1.2.8) lib/warden/manager.rb:34:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] rack (2.0.8) lib/rack/tempfile_reaper.rb:15:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] rack (2.0.8) lib/rack/etag.rb:25:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] rack (2.0.8) lib/rack/conditional_get.rb:25:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] rack (2.0.8) lib/rack/head.rb:12:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] rack (2.0.8) lib/rack/session/abstract/id.rb:259:in `context'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] rack (2.0.8) lib/rack/session/abstract/id.rb:253:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] activesupport (5.2.4.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] railties (5.2.4.1) lib/rails/rack/logger.rb:38:in `call_app'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `block in call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:28:in `tagged'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `tagged'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] rack (2.0.8) lib/rack/method_override.rb:22:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] rack (2.0.8) lib/rack/runtime.rb:22:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] activesupport (5.2.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] rack (2.0.8) lib/rack/sendfile.rb:111:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] actionpack (5.2.4.1) lib/action_dispatch/middleware/ssl.rb:74:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] railties (5.2.4.1) lib/rails/engine.rb:524:in `call'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
[c4d27567-8181-4f5a-9b1b-bc7acf7dd871] /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

```

Could someone help me?

**Comment by diegopolido** [comment]
It occurred because of Twilio Authy Application's configuration. I set the properties properly and everything is working just fine.

**Comment by philnash** [comment]
Ah, I was going to ask, was it the "Generic authenticator tokens" setting in your Authy Application?
